- ignore: {name: Avoid lambda}
- ignore: {name: Avoid lambda using `infix`}
- ignore: {name: Eta reduce}
- ignore: {name: Reduce duplication}
- ignore: {name: Redundant pure}
- ignore: {name: Use camelCase}
- ignore: {name: Use const}
- ignore: {name: Use head}
- ignore: {name: Use if}
- ignore: {name: Use list literal pattern}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Use uncurry}
- ignore: {name: Use <$>}
