name: advent-of-code
version: 0.1.0.0
github: Javran/advent-of-code
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
description: description

dependencies:
- base
- text
- bytestring

data-files:
- data/testdata/**/*.input.txt
- data/testdata/**/*.expect.txt

library:
  source-dirs: src
  dependencies:
    - vector
    - vector-algorithms
    - containers
    - filepath
    - http-types
    - http-client
    - http-client-tls
    - directory
    - time
    - turtle
    - split
    - once
    - template-haskell
    - mtl
    - memoize
    - data-ordlist
    - arithmoi
    - unordered-containers
    - strict
  ghc-options:
    - -Wall
    - -O2

executables:
  run-advent-of-code:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - advent-of-code
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - advent-of-code
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
