name: advent-of-code
version: 0.1.0.0
github: Javran/advent-of-code
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
description: description

dependencies:
- base
- text
- bytestring
- template-haskell
- containers
- foldl
- system-filepath
- turtle
- directory
- filepath

library:
  source-dirs: src
  dependencies:
    - vector
    - vector-algorithms
    - http-types
    - http-client
    - http-client-tls
    - time
    - split
    - once
    - mtl
    - memoize
    - data-ordlist
    - arithmoi
    - unordered-containers
    - strict
    - microstache
    - aeson
    - parser-combinators
    - mod
    - cryptohash-sha256
    - terminfo
    - html-conduit
    - xml-conduit
    - petbox
    - dlist
    - list-t
    - linear
    - lens
    - random
    - array
    - writer-cps-mtl
    - recursion-schemes
    - PSQueue
    - hashable
    - hashtables
    - semirings
    - z3
    - raw-strings-qq
    - monad-loops
    - monoidal-containers
    - newtype
    - psqueues
    - transformers
    - shower
    - union-find
    - mono-traversable
    - hmatrix
    - ghc-typelits-knownnat
  ghc-options:
    - -Wall
    - -O2
  # https://github.com/commercialhaskell/stack/issues/5503#issuecomment-799909211
  when:
    - condition: false
      other-modules:
        - Paths_advent_of_code

executables:
  run-advent-of-code:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - advent-of-code
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    when:
      - condition: false
        other-modules:
          - Paths_advent_of_code

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - advent-of-code
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
    when:
      - condition: false
        other-modules:
          - Paths_advent_of_code
