resolver: lts-18.20
packages:
- .

extra-deps:
- git: https://github.com/Javran/petbox.git
  commit: 8e921c41862dbe37ae8d957e88cea7961362e303
- z3-408.2
- PSQueue-1.1.0.1
- memoize-1.1.1
- monoidal-containers-0.6.2.0
- arithmoi-0.12.0.1
- QuickCheck-2.14.2
- shower-0.2.0.2
